# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "aws-runner"
    # Cloud Provider: AWS
    cloud: "aws"
    instance_type: "t3a.large"
    # Ubuntu-20.4, ami image
    machine_image: "ami-for-eu-west-1"
    preemptible: false
    region: "eu-west-1"
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-aws-runner"
