name: Create a pipeline and test it
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NXF_ANSI_LOG: false

jobs:
  RunTestWorkflow:
    runs-on: self-hosted
    env:
      NXF_ANSI_LOG: false
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - uses: actions/checkout@v3
        name: Check out source-code repository

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        env:
          AGENT_TOOLSDIRECTORY: ${{ runner.tool_cache }}
        with:
          python-version: 3.11

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: ${{ matrix.NXF_VER }}

      - name: Run nf-core/tools
        run: |
          echo "docker.userEmulation = false" > aws_docker.config
          echo "docker.fixOwnership = true" >> aws_docker.config
          nf-core --verbose --log-file log.txt create -n testpipeline -d "This pipeline is for testing" -a "Testing McTestface" --plain
          nextflow run nf-core-testpipeline -profile test,docker -c aws_docker.config --outdir ./results

      - name: Upload log file artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: nf-core-log-file
          path: .nextflow.log
