name: Python tests
# This workflow is triggered on pushes and PRs to the repository.
# Only run if we changed a Python file
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "docs/**"
      - "CHANGELOG.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "CHANGELOG.md"
  release:
    types: [published]
  workflow_dispatch:

# Cancel if a newer run with the same workflow name is queued
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup:
    runs-on: ["self-hosted"]
    strategy:
      matrix:
        python-version: ["3.8", "3.12"]
        runner: ["ubuntu-latest"]
        include:
          - runner: "ubuntu-20.04"
            python-version: "3.8"

    steps:
      - name: Check conditions
        id: conditions
        run: echo "run-tests=${{ github.ref == 'refs/heads/master' || (matrix.runner == 'ubuntu-20.04' && matrix.python-version == '3.8') }}" >> $GITHUB_ENV

    outputs:
      python-version: ${{ matrix.python-version }}
      runner: ${{ matrix.runner }}
      run-tests: ${{ env.run-tests }}

  # create a test matrix based on all python files in /tests
  list_tests:
    name: Get test file matrix
    runs-on: ["self-hosted"]
    outputs:
      tests: ${{ env.tests }}
    steps:
      - uses: actions/checkout@v4
        name: Check out source-code repository
      - name: List tests
        id: list_tests
        run:
          | # get all python files in /tests strting with test_ excluding test_modules, test_subworkflows and test_components
          echo "tests=$(find tests/test_* | sed 's/tests\///g' | jq -R -s -c '{test: (split("\n")[:-1])}')" >> $GITHUB_ENV

  test:
    name: Run ${{matrix.test}} with Python ${{ needs.setup.outputs.python-version }} on ${{ needs.setup.outputs.runner }}
    needs: [setup, list_tests]
    if: ${{ needs.setup.outputs.run-tests == 'true' }}
    runs-on: "self-hosted"
    strategy:
      matrix: ${{ fromJson(needs.list_tests.outputs.tests) }}
      fail-fast: false # run all tests even if one fails
    steps:
      - uses: actions/checkout@v4
        name: Check out source-code repository

      - name: Set up Python ${{ needs.setup.outputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ needs.setup.outputs.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -r requirements-dev.txt
          pip install -e .

      - name: Downgrade git to the Ubuntu official repository's version
        if: ${{ needs.setup.outputs.runner == 'ubuntu-20.04' && needs.setup.outputs.python-version == '3.8' }}
        run: |
          sudo apt update
          sudo apt remove -y git git-man
          sudo add-apt-repository --remove ppa:git-core/ppa
          sudo apt install -y git
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_ENV

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Cache nf-test installation
        id: cache-software
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/nf-test
            /home/runner/.nf-test/nf-test.jar
          key: ${{ runner.os }}-${{ env.NFTEST_VER }}-nftest

      - name: Install nf-test
        if: steps.cache-software.outputs.cache-hit != 'true'
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/
      - name: print nextflow.config
        run: cat /opt/actions-runner/nextflow.config

      - name: Test with pytest
        run: |
          python3 -m pytest tests/${{matrix.test}} --color=yes --cov-report=xml --cov-config=.github/.coveragerc --cov=nf_core || exit_code=$?
          # don't fail if no tests were collected, e.g. for test_licence.py
          if [ "${exit_code}" -eq 5 ]; then
            echo "No tests were collected"
            exit 0
          elif [ "${exit_code}" -ne 0 ]; then
            echo "Tests failed with exit code ${exit_code}"
            exit 1
          fi

      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage${{ matrix.test }}
          path: .coverage

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Download all artifacts
        # Downloads coverage1, coverage2, etc.
        uses: actions/download-artifact@v3

      - name: Print working directory and list files
        run: |
          pwd
          ls -l

      - name: Run coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage xml -i

      - uses: codecov/codecov-action@v3
