name: Generate images for docs
on:
  workflow_dispatch:
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: setup.py

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Cache nf-test installation
        id: cache-software
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/bin/nf-test
            /home/runner/.nf-test/nf-test.jar
          key: ${{ runner.os }}-nftest-${{ env.date }}

      - name: Install nf-test
        if: steps.cache-software.outputs.cache-hit != 'true'
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Install nf-core/tools
        run: pip install git+https://github.com/nf-core/tools.git@dev

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1
        env:
          COLUMNS: 100
          HIDE_PROGRESS: "true"
        with:
          commit_changes: "true"
          clean_img_paths: docs/images/*.svg
          terminal_width: 100
          before_command: >
            which nextflow &&
            which nf-core &&
            nextflow -version &&
            nf-core --version
