name: nf-core/tools release API docs
on:
  release:
    types: [published]
  push:
    branches: dev
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        default: "dev"

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  api-docs:
    # checkout the nf-core/website repo, generate the docs with lazydocs and copy to `src/content/tools/$release_version` and open a PR with the changes on the website repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.nf_core_bot_auth_token }}

      - name: Checkout nf-core/website
        uses: actions/checkout@v3
        with:
          repository: nf-core/website
          token: ${{ secrets.nf_core_bot_auth_token }}
          path: website

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install lazydocs
        run: pip install lazydocs

      - name: Generate API docs
        run: |
          lazydocs nf-core/tools -o website/src/content/tools/${{github.ref_name}} --force \
            --src-base-url="https://github.com/nf-core/tools/blob/${{github.ref_name}}/" \
            --overview-file="index.md"

      - name: Commit and push changes
        run: |
          cd website
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          git checkout -b update-tools-api-docs
          git add src/content/tools/${{github.ref_name}}
          git remote add nf-core-website https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/nf-core/website.git
          git push nf-core-website update-tools-api-docs
